# Generated by Django 4.2.16 on 2024-10-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True, unique=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('og_image_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'verbose_name_plural': 'All News',
                'ordering': ['-published_at', '-updated_at', 'title'],
            },
        ),
    ]
